version: 2
jobs:
  build:
    docker:
      - image: stackfeed/circle-shell
    environment:
      PROJECT: bitcoind
      NAMESPACE: plasmops
      PUSH_NAMESPACES: plasmops
      CONTINUOUS_INTEGRATION: true

    steps:
      - checkout
      - setup_remote_docker
      -
        run:
          name: Install ci-scripts
          command: |
            echo 'export PATH=$PATH:~/ci-scripts' >> $BASH_ENV
            wget -qO - https://github.com/stackfeed/ci-scripts/raw/master/install.sh | sh -s -- -r v0.2
      -
        run:
          name: Setup dependencies
          command: |
            latests=$(wget -qO - https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/.latests)
            version=${CIRCLE_TAG}
            [ -n "$version" ] || version=$(echo "${latests}" | cut -f1 -d' ')

            printf 'export LATESTS=%s\n' ${latests} >> $BASH_ENV
            printf 'export VERSION=%s\n' ${version} >> $BASH_ENV
      -
        run:
          name: Build docker image
          command: |
            docker-build -v $VERSION -l "$LATESTS" "$NAMESPACE/$PROJECT" \
              --build-arg release=${VERSION} \
              --build-arg version=${VERSION%%-*} \
                -f Dockerfile ./
      -
        run:
          name: Publish docker image
          command: |
            # confitionaly skip pushes
            ( echo "$PUSH_NAMESPACES" | grep -qw "${CIRCLE_PROJECT_USERNAME}" ) || exit 0
            [ -n "${CIRCLE_TAG}" ] || exit 0

            docker-push -r "^$NAMESPACE/$PROJECT:?.*"
            # update microbadger
            # curl -XPOST "https://hooks.microbadger.com/images/${NAMESPACE}/${PROJECT}/${MICROBADGER_TOKEN}"

workflows:
  version: 2
  default:
    jobs:
      - build

  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^(\d+\.?)+/
